<?php
/**
 * Authkey API Authentication Keys for xoops.org
 *
 * You may not change or alter any portion of this comment or credits
 * of supporting developers from this source code or any supporting source code
 * which is considered copyrighted (c) material of the original comment or credit authors.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * @copyright       (c) 2000-2019 Chronolabs Cooperative (8Bit.snails.email)
 * @license             GNU GPL 2 (http://www.gnu.org/licenses/gpl-2.0.html)
 * @package             authkey
 * @since               1.0.7
 * @author              Simon Antony Roberts <wishcraft@users.sourceforge.net>
 * @link                https://sourceforge.net/p/xoops/svn/HEAD/tree/XoopsModules/authkey
 */




    // Email Subjects
    define('_MI_AUTHKEY_SUBJECT_ISSUINGKEY','Xoops.org ~ Issuing API Key: /?xoopskey=%s');
    define('_MI_AUTHKEY_SUBJECT_LIMITREACHED','Xoops.org ~ %s Limit of API\'s Polling Reached over by: %s');
    define('_MI_AUTHKEY_SUBJECT_OVERLIMIT', 'Xoops.org API your limit: %s has polled over by: %s!');
    
    //Title Template
    define('_MI_AUTHKEY_KEY_TITLE', 'XoopsKey for: %s');
    define('_MI_AUTHKEY_APIS', 'API\'s Requiring Xoopskey');
    
    // Periodically Based Constants
    define('_MI_AUTHKEY_PERIODICALLY_HOUR', 'Hourly');
    define('_MI_AUTHKEY_PERIODICALLY_DAY', 'Daily');
    define('_MI_AUTHKEY_PERIODICALLY_WEEK', 'Weekly');
    define('_MI_AUTHKEY_PERIODICALLY_MONTH', 'Monthly');
    define('_MI_AUTHKEY_PERIODICALLY_QUARTER', 'Quarterly');
    define('_MI_AUTHKEY_PERIODICALLY_YEAR', 'Yearly');
    
    // Periodical Based Constants
    define('_MI_AUTHKEY_PERIODICAL_HOUR', 'Hour');
    define('_MI_AUTHKEY_PERIODICAL_DAY', 'Day');
    define('_MI_AUTHKEY_PERIODICAL_WEEK', 'Week');
    define('_MI_AUTHKEY_PERIODICAL_MONTH', 'Month');
    define('_MI_AUTHKEY_PERIODICAL_QUARTER', 'Quarter');
    define('_MI_AUTHKEY_PERIODICAL_YEAR', 'Year');
    
    // Admin Menu
	define('_MI_AUTHKEY_ADMENU0','Dashboard');
	define('_MI_AUTHKEY_ADMENU1','Auth/Xoops Keys');
	define('_MI_AUTHKEY_ADMENU2','Key Statistics');
	define('_MI_AUTHKEY_ADMENU3','Permissions');
	define('_MI_AUTHKEY_ADMENU4','About Module');
	define('_MI_AUTHKEY_ADMENU5','API\'s Available');
	
	// Admin Menu Icons
	define('_MI_AUTHKEY_ADMENU0_ICON','assets/images/32x32/dashboard.png');
	define('_MI_AUTHKEY_ADMENU1_ICON','assets/images/32x32/administration.png');
	define('_MI_AUTHKEY_ADMENU2_ICON','assets/images/32x32/stats.png');
	define('_MI_AUTHKEY_ADMENU3_ICON','assets/images/32x32/permissions.png');
	define('_MI_AUTHKEY_ADMENU4_ICON','assets/images/32x32/about.png');
	define('_MI_AUTHKEY_ADMENU5_ICON','assets/images/32x32/exec.png');
	
	// LANGUAGE DESCRIPTIONS  
	define('_MI_AUTHKEY_API_REPORTING','Send API Overall Reports to these groups!');
	define('_MI_AUTHKEY_API_REPORTING_DESC','The API Reports will be sent to these groups when they are made monthly, 6 monthly, yearly or biannually!');
	define('_MI_AUTHKEY_MINUMUM_LINES','Minimum lines of data sent in *.csv report');
	define('_MI_AUTHKEY_MINUMUM_LINES_DESC','This is the minimum lines of data that have to exist in a report to be sent to API, User or Owner Reports!');
	define('_MI_AUTHKEY_TMP_PATH','Temporary Write Path');
	define('_MI_AUTHKEY_TMP_PATH_DESC','This is the full path to your temporary write path');
	define('_MI_AUTHKEY_DELETE_SECONDS','Deleting statistical data when it is!');
	define('_MI_AUTHKEY_DELETE_SECONDS_DESC','This is how long statistics are kept in retention on the statistics tabling!');
	define('_MI_AUTHKEY_AUTOGENERATED','Auto-generate users 1st Authentication Key');
	define('_MI_AUTHKEY_AUTOGENERATED_DESC','When this is enabled the module will periodically search for users with no authkey/xoopskey allocate and generate them one!');
	define('_MI_AUTHKEY_AUTOGENERATED_SECONDS','How often should we search for auto-generating 1st time authkeys');
	define('_MI_AUTHKEY_AUTOGENERATED_SECONDS_DESC','This is the total amount of time between queuing for searching for unallocate users for an authkey/xoopskey!');
	define('_MI_AUTHKEY_NUMBER_AUTOGENERATED','Number unallocated authkey/xoopskey users to generate');
	define('_MI_AUTHKEY_NUMBER_AUTOGENERATED_DESC','This is the total number of users allowed to be allocated a authkey/xoopskey at any one time of the auto generation sessioning!');
	define('_MI_AUTHKEY_POLLING_SECONDS','Number of minutes to wait before saving queue cache polling to database');
	define('_MI_AUTHKEY_POLLING_SECONDS_DESC','When this is set to a period, it will save the file base tabled data to the database in this period allocated!');
	define('_MI_AUTHKEY_PRELOAD_SECONDS','Preload Crons Fire in this Period and then wait for it till firing again');
	define('_MI_AUTHKEY_PRELOAD_SECONDS_DESC','');
	define('_MI_AUTHKEY_LIMITED','API Are Limited to Calls Per Period');
	define('_MI_AUTHKEY_LIMITED_DESC','When this is enabled the API are limited to the number of calls that can be done to them per period!');
	define('_MI_AUTHKEY_LIMIT_HOUR','API Calls Allowed Hourly');
	define('_MI_AUTHKEY_LIMIT_HOUR_DESC','This is the number of calls that can be made in an hour by default.');
	define('_MI_AUTHKEY_LIMIT_DAY','API Calls Allowed Daily');
	define('_MI_AUTHKEY_LIMIT_DAY_DESC','This is the number of calls that can be made in a day by default.');
	define('_MI_AUTHKEY_LIMIT_WEEK','API Calls Allowed Weekly');
	define('_MI_AUTHKEY_LIMIT_WEEK_DESC','This is the number of calls that can be made in a week by default.');
	define('_MI_AUTHKEY_LIMIT_MONTH','API Calls Allowed Monthly');
	define('_MI_AUTHKEY_LIMIT_MONTH_DESC','This is the number of calls that can be made in a month by default.');	
	define('_MI_AUTHKEY_LIMIT_QUARTER','API Calls Allowed Quarterly');
	define('_MI_AUTHKEY_LIMIT_QUARTER_DESC','This is the number of calls that can be made in a quarter of a year by default.');	
	define('_MI_AUTHKEY_LIMIT_YEAR','API Calls Allowed Yearly');
	define('_MI_AUTHKEY_LIMIT_YEAR_DESC','This is the number of calls that can be made in a year by default.');	
	define('_MI_AUTHKEY_PURCHASE_HOUR','Purchase to increase limit hourly by');
	define('_MI_AUTHKEY_PURCHASE_HOUR_DESC','This is the number of calls you can increase all the limits by hour with a one off purchase through <em>xpayment</em>');	
	define('_MI_AUTHKEY_PURCHASE_DAY','Purchase to increase limit daily by');
	define('_MI_AUTHKEY_PURCHASE_DAY_DESC','This is the number of calls you can increase all the limits by a day with a one off purchase through <em>xpayment</em>');
	define('_MI_AUTHKEY_PURCHASE_WEEK','Purchase to increase limit weekly by');
	define('_MI_AUTHKEY_PURCHASE_WEEK_DESC','This is the number of calls you can increase all the limits by a week with a one off purchase through <em>xpayment</em>');
	define('_MI_AUTHKEY_PURCHASE_MONTH','Purchase to increase limit monthly by');
	define('_MI_AUTHKEY_PURCHASE_MONTH_DESC','This is the number of calls you can increase all the limits by a month with a one off purchase through <em>xpayment</em>');
	define('_MI_AUTHKEY_PURCHASE_QUARTER','Purchase to increase limit quarterly by');
	define('_MI_AUTHKEY_PURCHASE_QUARTER_DESC','This is the number of calls you can increase all the limits by a quarter of a year with a one off purchase through <em>xpayment</em>');
	define('_MI_AUTHKEY_PURCHASE_YEAR','Purchase to increase limit yearly by');
	define('_MI_AUTHKEY_PURCHASE_YEAR_DESC','This is the number of calls you can increase all the limits for a year with a one off purchase through <em>xpayment</em>');
	define('_MI_AUTHKEY_PURCHASE_PRICE','Purchase price to increase limit');
	define('_MI_AUTHKEY_PURCHASE_PRICE_DESC','This is the one off purchase price for calling tokens by hourly+++');	
	define('_MI_AUTHKEY_PURCHASE_NOMIAL','Purchase price currency');
	define('_MI_AUTHKEY_PURCHASE_NOMIAL_DESC','The currency use for the one off purchase!');	
	define('_MI_AUTHKEY_XPAYMENT_URL','xPayment Module for recieving payments');
	define('_MI_AUTHKEY_XPAYMENT_URL_DESC','This is the URL used for passing to xPayment transaction invoices!');
	define('_MI_AUTHKEY_HTACCESS','Enabled HTACCESS SEO');
	define('_MI_AUTHKEY_HTACCESS_DESC','This enables SEO');
	define('_MI_AUTHKEY_BASEURL','Base URL for SEO');
	define('_MI_AUTHKEY_BASEURL_DESC','Base URL for SEO');
	define('_MI_AUTHKEY_ENDOFURL','End of URL');
	define('_MI_AUTHKEY_ENDOFURL_DESC','File Extension to HTML Files');
	define('_MI_AUTHKEY_ENDOFURLPDF','End of URL');
	define('_MI_AUTHKEY_ENDOFURLPDF_DESC','File Extension to Adobe Acrobat (PDF) Files');

	// Permission Tokens
	define('_MI_AUTHKEY_PERM_AUTHKEY', 'authkey');
	define('_MI_AUTHKEY_PERM_UNLIMITEDCALLS', 'unlimited');
	define('_MI_AUTHKEY_PERM_UNLIMITEDCALLS_ID', 10000);
	define('_MI_AUTHKEY_PERM_INCREASEONAVG', 'increaseavg');
	define('_MI_AUTHKEY_PERM_INCREASEONAVG_ID', 10010);
	define('_MI_AUTHKEY_PERM_ALLOWPURCHASING', 'purchasing');
	define('_MI_AUTHKEY_PERM_ALLOWPURCHASING_ID', 10020);
	define('_MI_AUTHKEY_PERM_ALLOWCREATING', 'creating');
	define('_MI_AUTHKEY_PERM_ALLOWCREATING_ID', 10030);
	define('_MI_AUTHKEY_PERM_ALLOWREISSUED', 'reissuing');
	define('_MI_AUTHKEY_PERM_ALLOWREISSUED_ID', 10040);
	define('_MI_AUTHKEY_PERM_ALLOWVIEWING', 'viewing');
	define('_MI_AUTHKEY_PERM_ALLOWVIEWING_ID', 10050);
	define('_MI_AUTHKEY_PERM_ALLOWEDITING', 'editing');
	define('_MI_AUTHKEY_PERM_ALLOWEDITING_ID', 10060);
	define('_MI_AUTHKEY_PERM_ALLOWDELETING', 'deleting');
	define('_MI_AUTHKEY_PERM_ALLOWDELETING_ID', 10070);
	define('_MI_AUTHKEY_PERM_STOPISSUINGKEY', 'noissuing');
	define('_MI_AUTHKEY_PERM_STOPISSUINGKEY_ID', 10080);
	define('_MI_AUTHKEY_PERM_EMAILUSERMONTHLY', 'usermonthly');
	define('_MI_AUTHKEY_PERM_EMAILUSERMONTHLY_ID', 10090);
	define('_MI_AUTHKEY_PERM_EMAILUSER6MONTHLY', 'user6monthly');
	define('_MI_AUTHKEY_PERM_EMAILUSER6MONTHLY_ID', 10110);
	define('_MI_AUTHKEY_PERM_EMAILUSER12MONTHLY', 'user12monthly');
	define('_MI_AUTHKEY_PERM_EMAILUSER12MONTHLY_ID', 10120);
	define('_MI_AUTHKEY_PERM_EMAILUSER24MONTHLY', 'user24monthly');
	define('_MI_AUTHKEY_PERM_EMAILUSER24MONTHLY_ID', 10130);
	define('_MI_AUTHKEY_PERM_EMAILOWNERMONTHLY', 'ownermonthly');
	define('_MI_AUTHKEY_PERM_EMAILOWNERMONTHLY_ID', 10140);
	define('_MI_AUTHKEY_PERM_EMAILOWNER6MONTHLY', 'owner6monthly');
	define('_MI_AUTHKEY_PERM_EMAILOWNER6MONTHLY_ID', 10150);
	define('_MI_AUTHKEY_PERM_EMAILOWNER12MONTHLY', 'owner12monthly');
	define('_MI_AUTHKEY_PERM_EMAILOWNER12MONTHLY_ID', 10160);
	define('_MI_AUTHKEY_PERM_EMAILOWNER24MONTHLY', 'owner24monthly');
	define('_MI_AUTHKEY_PERM_EMAILOWNER24MONTHLY_ID', 10170);
	
	
	// Permission Descriptions
	define('_MI_AUTHKEY_PERM_FORMTITLE', 'Permissions for AuthKeys/XoopsKeys!');
	define('_MI_AUTHKEY_PERM_UNLIMITEDCALLS_DESC', 'Unlimited API Polling!');
	define('_MI_AUTHKEY_PERM_INCREASEONAVG_DESC', 'Increase Limit Base in Adverages');
	define('_MI_AUTHKEY_PERM_ALLOWPURCHASING_DESC', 'Allow purchasing of more polling tokens');
	define('_MI_AUTHKEY_PERM_ALLOWCREATING_DESC', 'Allow creation of 2nd+ AuthKey/XoopsKey');
	define('_MI_AUTHKEY_PERM_ALLOWREISSUED_DESC', 'Allow Re-issuing of key\'s');
	define('_MI_AUTHKEY_PERM_ALLOWVIEWING_DESC', 'Allow Viewing + Statistics profiles');
	define('_MI_AUTHKEY_PERM_ALLOWEDITING_DESC', 'Allow Editing of Xoopskey/Authkey');
	define('_MI_AUTHKEY_PERM_ALLOWDELETING_DESC', 'Allow Deleting of Xoopskey/Authkey');
	define('_MI_AUTHKEY_PERM_STOPISSUINGKEY_DESC', 'Stop all issuing of keys to this group');
	define('_MI_AUTHKEY_PERM_EMAILUSERMONTHLY_DESC', 'Email Monthly User *.csv Report');
	define('_MI_AUTHKEY_PERM_EMAILUSER6MONTHLY_DESC', 'Email 6 Month\'s User *.csv Report');
	define('_MI_AUTHKEY_PERM_EMAILUSER12MONTHLY_DESC', 'Email Yearly User *.csv Report');
	define('_MI_AUTHKEY_PERM_EMAILUSER24MONTHLY_DESC', 'Email Biannual User *.csv Report');
	define('_MI_AUTHKEY_PERM_EMAILOWNERMONTHLY_DESC', 'Email Monthly Key Owner\'s *.csv Report');
	define('_MI_AUTHKEY_PERM_EMAILOWNER6MONTHLY_DESC', 'Email 6 Month\'s Key Owner\'s *.csv Report');
	define('_MI_AUTHKEY_PERM_EMAILOWNER12MONTHLY_DESC', 'Email Yearly Key Owner\'s *.csv Report');
	define('_MI_AUTHKEY_PERM_EMAILOWNER24MONTHLY_DESC', 'Email Biannual Key Owner\'s *.csv Report');
	
	// MENUs
	define('_MI_AUTHKEY_ADMENU0','Dashboard');
	define('_MI_AUTHKEY_ADMENU8','About XCentre');
	
	// MENU ICONS?IMAGES
	define('_MI_AUTHKEY_ADMENU0_ICON','../../Frameworks/moduleclasses/icons/32/home.png');
	define('_MI_AUTHKEY_ADMENU8_ICON','../../Frameworks/moduleclasses/icons/32/about.png');
		
?>